version: "3.9"
services:
  web:
    build: .
    ports: 
      - "80:80"
    volumes: 
      - ./htdocs:/var/www/html
      - ./docker-php.conf:/etc/apache2/conf-available/docker-php.conf
      - ./sources.list:/etc/apt/sources.list
    environment:
      TZ: Asia/Shanghai,
    privileged: true
  mysql:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    command: 
      --default-authentication-plugin=mysql_native_password
      --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 611611
    volumes:
      - data-mysql:/var/lib/mysql
      - ./htdocs:/data
  redis:
    environment:
      TZ: Asia/Shanghai
    image: redis:alpine
    volumes:
      - data-redis:/data
volumes:
  data-mysql:
  data-redis: